#!/bin/zsh
#
# ralph-v2.sh — bash-orchestrated implement → test → commit → review → fix loop.
#
# Design philosophy: bash owns ALL determinism (beads, git, the test gate,
# commits, control flow). The agents are pure functions invoked via `claude -p`
# and NEVER touch beads — bash is the only beads-aware layer. Each cognitive
# step is a separate, fresh-context agent call; bash owns the data flow between
# them.
#
# This does NOT replace ralph.sh (the v1 single-agent loop). It is the v2 design.
#
# Per task, the loop:
#   1. picks + claims the top ready task (bash)
#   2. renders a clean markdown spec and hands it to the implement agent
#   3. runs `task test` itself as an independent gate (ground truth, not the
#      agent's word); red routes into the fix loop with the test output
#   4. commits at known-green (message generated by a cheap dedicated agent)
#   5. runs the review agent (deep, no verdict), feeds its findings to a
#      separate judge agent that emits a machine-readable VERDICT, then loops
#      fix → re-test → re-commit → re-review until PASS (capped)
#   6. closes the task (bash) only on PASS
#
# Policy (MVP): halt on the first failure. Full per-task logs land in
# .ralph/runs/<id>/ so each run is a dataset for improving the agents.
#
# Usage: ./ralph-v2.sh <iterations>

set -u  # Deliberately NOT `set -e`: we capture exit codes per stage and route
        # failures ourselves. A global errexit would abort mid-command and
        # defeat the whole "bash owns the control flow" design.

# ------------------------------------------------------------------ config ----
MAX_FIX_ROUNDS=3                                   # cap on review-driven fix cycles
MAX_TEST_FIX_ATTEMPTS=3                            # cap on test-gate fix cycles
VERDICT_RETRIES=1                                  # extra tries to get a parseable verdict
TEST_CMD="task test"                               # the independent test gate
COMMIT_MODEL="claude-haiku-4-5-20251001"           # cheap model for commit messages
RUNS_DIR=".ralph/runs"

# ----------------------------------------------------------------- helpers ----
log()  { print -r -- "[ralph-v2] $*"; }
die()  { print -r -- "[ralph-v2] FATAL: $*" >&2; exit 1; }

# Stop the run cleanly: record why on the bead (leaving it claimed/in_progress
# so the next run won't re-grab it) and exit non-zero. MVP policy = halt on
# first failure.
halt() {
  local id="$1" reason="$2"
  log "HALT on ${id}: ${reason}"
  bd comment "$id" "ralph-v2 halted: ${reason}" >/dev/null 2>&1 || true
  exit 1
}

# Render a beads task object (JSON on stdin) into a clean markdown spec. The
# agent never sees beads-shaped fields — just a task to implement.
render_spec() {
  jq -r '
    "# \(.title)\n\n" +
    "## Description\n\(.description // "(none provided)")\n\n" +
    "## Acceptance Criteria\n\(.acceptance_criteria // "(none provided)")"
  '
}

# Run a headless agent. $1=stdout-log $2=prompt. stderr goes to <log>.err so the
# stdout log stays clean for first-line verdict parsing. Returns claude's exit
# code (NOT captured in a subshell, so the caller sees the real status).
run_agent() {
  local logfile="$1" prompt="$2"
  # claude -p "$prompt" >"$logfile" 2>"${logfile}.err"
  pi -p "$prompt" >"$logfile" 2>"${logfile}.err"
}

# Generate a commit subject from the staged diff using a cheap model. Writes the
# message to $1. The agent reads the diff via its own tools; output is the
# message only.
gen_commit_subject() {
  local outfile="$1"
  # claude -p 'Run `git diff --cached` to see the staged changes, then output ONLY a concise conventional-commit subject line (<= 72 chars) describing them. No body, no code fences, no quotes, no preamble — just the subject line.' \
  #   --model "$COMMIT_MODEL" >"$outfile" 2>/dev/null
  pi -p 'Run `git diff --cached` to see the staged changes, then output ONLY a concise conventional-commit subject line (<= 72 chars) describing them. No body, no code fences, no quotes, no preamble — just the subject line.' >"$outfile" 2>/dev/null
}

# First non-empty line of a file, stripped of CR and surrounding whitespace.
first_line() {
  tr -d '\r' <"$1" 2>/dev/null \
    | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' \
    | grep -m 1 -v '^$'
}

# Run the judge agent on a findings file until it returns a parseable verdict
# (capped by VERDICT_RETRIES). The judge owns the machine-readable contract; we
# only ever interpolate paths into its prompt, never model text. Sets two
# globals for the caller: JUDGE_VERDICT (PASS|NEEDS_CHANGES|BLOCKED, or empty if
# the judge never produced a parseable verdict) and JUDGE_LOG (path to the
# winning judge log). Returns 0 on a parseable verdict, 1 otherwise.
#   $1 = findings file (the reviewer/verifier output the judge weighs)
#   $2 = spec path
#   $3 = log path prefix ("-attempt-N.log" is appended per attempt)
judge_verdict() {
  local findings="$1" spec="$2" prefix="$3"
  local attempt=0 jlog line1
  JUDGE_VERDICT=""
  JUDGE_LOG=""
  while [ "$attempt" -le "$VERDICT_RETRIES" ]; do
    attempt=$(( attempt + 1 ))
    jlog="${prefix}-attempt-${attempt}.log"
    log "judge attempt ${attempt} (findings = ${findings})"
    if ! run_agent "$jlog" "/judge-review-v2 ${findings} ${spec}"; then
      log "judge agent exited non-zero (attempt ${attempt})"
      continue
    fi
    line1="$(first_line "$jlog")"
    case "$line1" in
      "VERDICT: PASS"|"VERDICT: NEEDS_CHANGES"|"VERDICT: BLOCKED")
        JUDGE_VERDICT="${line1#VERDICT: }"
        JUDGE_LOG="$jlog"
        return 0
        ;;
      *)
        log "unparseable verdict (attempt ${attempt}): '${line1}'"
        ;;
    esac
  done
  return 1
}

# --------------------------------------------------------------- arguments ----
[ $# -ge 1 ] || die "usage: $0 <iterations>"
ITERATIONS="$1"
[[ "$ITERATIONS" == <-> ]] || die "iterations must be a positive integer"

# --------------------------------------------------------------- preflight ----
command -v bd >/dev/null 2>&1 || die "bd not found on PATH"
command -v jq >/dev/null 2>&1 || die "jq not found on PATH"
command -v pi >/dev/null 2>&1 || die "pi not found on PATH"

ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || die "not inside a git repository"
cd "$ROOT" || die "cannot cd to repo root $ROOT"

BRANCH="$(git rev-parse --abbrev-ref HEAD)"
[ "$BRANCH" = "main" ] && die "refusing to run on 'main' — check out a feature branch first"
log "branch: $BRANCH"

log "preflight: running '$TEST_CMD' to confirm a green starting tree"
if ! eval "$TEST_CMD" >/dev/null 2>&1; then
  die "preflight test run failed — the tree is already broken; fix it before starting"
fi
log "preflight: tree is green"

# ============================================================== main loop =====
for (( i = 1; i <= ITERATIONS; i++ )); do
  log "================= iteration ${i} / ${ITERATIONS} ================="

  # ---- pick the top ready task (bash owns beads) --------------------------
  ready_json="$(BD_JSON_ENVELOPE=1 bd ready --json 2>/dev/null)" || die "bd ready failed"
  ready_count="$(print -r -- "$ready_json" | jq '.data | length')"
  if [ "$ready_count" -eq 0 ]; then
    log "no ready tasks remaining — PRD complete after $((i - 1)) iteration(s)"
    exit 0
  fi

  task_json="$(print -r -- "$ready_json" | jq -c '.data[0]')"
  id="$(print -r -- "$task_json" | jq -r '.id')"
  title="$(print -r -- "$task_json" | jq -r '.title')"
  log "task: ${id} — ${title}"

  rundir="${RUNS_DIR}/${id}"
  mkdir -p "$rundir"

  # ---- render the spec and claim ------------------------------------------
  print -r -- "$task_json" | render_spec >"${rundir}/spec.md"
  spec_path="${ROOT}/${rundir}/spec.md"

  bd update "$id" --claim >/dev/null || die "failed to claim ${id}"
  base="$(git rev-parse HEAD)" || die "git rev-parse HEAD failed"
  log "claimed ${id}; base = ${base}"

  # ---- implement ----------------------------------------------------------
  log "implementing..."
  run_agent "${rundir}/implement.log" "/implement-task-v2 ${spec_path}" \
    || halt "$id" "implement agent exited non-zero"

  # ---- already-complete verification (no-op implement) --------------------
  # Tasks can overlap, so the implement agent may correctly judge a task already
  # done and make no changes. Rather than halt, independently verify the spec's
  # acceptance criteria against the CURRENT codebase: a dedicated verifier (there
  # is no diff to review) emits findings, and the SAME judge decides the verdict.
  #   PASS          -> nothing to build; close the task with no new commits.
  #   NEEDS_CHANGES -> the task was wrongly skipped; route the findings to the
  #                    fix agent and fall through into the normal pipeline.
  #   BLOCKED       -> halt for a human.
  if [ -z "$(git status --porcelain)" ]; then
    log "implement produced no changes — verifying the task is already complete"

    verify_log="${rundir}/verify-complete.log"
    run_agent "$verify_log" "/verify-complete-v2 ${spec_path}" \
      || halt "$id" "verify-complete agent exited non-zero"
    [ -s "$verify_log" ] || halt "$id" "verify-complete agent produced empty output"

    judge_verdict "${ROOT}/${verify_log}" "$spec_path" "${rundir}/verify-judge" \
      || halt "$id" "judge failed to return a parseable verdict $(( VERDICT_RETRIES + 1 ))x (already-complete verification)"

    # Durable record on the bead (same shape as the review-loop comment).
    verify_comment="${rundir}/bead-comment-verify.md"
    {
      print -r -- "## ralph-v2 already-complete verification — verdict: ${JUDGE_VERDICT}"
      print -r -- ""
      print -r -- "_Judge rationale:_"
      tail -n +2 "$JUDGE_LOG"
      print -r -- ""
      print -r -- "---"
      print -r -- ""
      cat "$verify_log"
    } >"$verify_comment"
    bd comment "$id" --file "$verify_comment" >/dev/null 2>&1 || log "warn: bd comment failed for ${id}"

    case "$JUDGE_VERDICT" in
      PASS)
        log "verified already-complete; closing ${id} with no new commits"
        bd close "$id" --reason "ralph-v2: verified already-complete (no changes needed), review PASS" >/dev/null \
          || die "failed to close ${id}"
        log "closed ${id}"
        continue  # next iteration; nothing to test, commit, or review
        ;;
      BLOCKED)
        halt "$id" "judge returned BLOCKED during already-complete verification"
        ;;
      NEEDS_CHANGES)
        log "judge disagrees the acceptance criteria are met; routing to fix"
        run_agent "${rundir}/fix-verify.log" "/fix-task-v2 ${ROOT}/${verify_log}" \
          || halt "$id" "fix agent (already-complete verification) exited non-zero"
        if [ -z "$(git status --porcelain)" ]; then
          halt "$id" "fix agent produced no changes after verification flagged unmet acceptance criteria"
        fi
        log "fix produced changes; continuing into the standard test/commit/review pipeline"
        # fall through to the test gate below
        ;;
    esac
  fi

  # ---- test gate (independent; bash runs the tests, not the agent) --------
  # Red gate routes into the fix loop with the failing test output as feedback.
  test_attempt=0
  while true; do
    tlog="${rundir}/test-${test_attempt}.log"
    log "test gate (attempt ${test_attempt}): ${TEST_CMD}"
    if eval "$TEST_CMD" >"$tlog" 2>&1; then
      log "tests green"
      break
    fi
    if [ "$test_attempt" -ge "$MAX_TEST_FIX_ATTEMPTS" ]; then
      halt "$id" "tests still failing after ${MAX_TEST_FIX_ATTEMPTS} fix attempt(s)"
    fi
    test_attempt=$(( test_attempt + 1 ))
    log "tests red; fix attempt ${test_attempt} (feedback = ${tlog})"
    run_agent "${rundir}/fix-test-${test_attempt}.log" "/fix-task-v2 ${ROOT}/${tlog}" \
      || halt "$id" "fix agent (test) exited non-zero"
  done

  # ---- commit at known-green (full history: one commit per stage) ---------
  git add -A
  gen_commit_subject "${rundir}/commit-msg-impl.txt"
  subject="$(first_line "${rundir}/commit-msg-impl.txt")"
  [ -z "$subject" ] && subject="implement ${id}"
  git commit -q -m "impl(${id}): ${subject}" || die "commit failed for ${id}"
  log "committed: impl(${id}): ${subject}"

  # ---- review / judge / fix loop (bash-owned) -----------------------------
  # Responsibilities are split: the REVIEW agent finds everything (no verdict),
  # then a separate JUDGE agent reads that review and decides the verdict. The
  # judge owns the machine-readable contract; the reviewer is free to be as
  # verbose as it likes without risking the loop.
  round=0
  while true; do
    round=$(( round + 1 ))
    if [ "$round" -gt "$MAX_FIX_ROUNDS" ]; then
      halt "$id" "review did not converge after ${MAX_FIX_ROUNDS} fix round(s)"
    fi

    # --- review (deep, free-form, no verdict) ------------------------------
    review_log="${rundir}/review-round-${round}.log"
    log "review round ${round}"

    run_agent "$review_log" "/review-task-v2 ${base} ${spec_path}" \
      || halt "$id" "review agent exited non-zero (round ${round})"
    if [ ! -s "$review_log" ]; then
      halt "$id" "review agent produced empty output (round ${round})"
    fi

    # --- judge (owns the VERDICT contract; retry on a contract miss) -------
    judge_verdict "${ROOT}/${review_log}" "$spec_path" "${rundir}/judge-round-${round}" \
      || halt "$id" "judge failed to return a parseable verdict $(( VERDICT_RETRIES + 1 ))x"
    verdict="$JUDGE_VERDICT"
    judge_log="$JUDGE_LOG"

    # Mirror the verdict + full review onto the bead as the durable record.
    combined="${rundir}/bead-comment-round-${round}.md"
    {
      print -r -- "## ralph-v2 review round ${round} — verdict: ${verdict}"
      print -r -- ""
      print -r -- "_Judge rationale:_"
      tail -n +2 "$judge_log"
      print -r -- ""
      print -r -- "---"
      print -r -- ""
      cat "$review_log"
    } >"$combined"
    bd comment "$id" --file "$combined" >/dev/null 2>&1 || log "warn: bd comment failed for ${id}"

    case "$verdict" in
      PASS)
        log "judge PASS on round ${round}"
        break
        ;;
      BLOCKED)
        halt "$id" "judge returned BLOCKED on round ${round}"
        ;;
      NEEDS_CHANGES)
        log "judge NEEDS_CHANGES on round ${round}; running fix"
        # Feedback = the reviewer's findings (already a file, no verdict line to
        # strip). We only ever interpolate a path, never model text.
        run_agent "${rundir}/fix-round-${round}.log" "/fix-task-v2 ${ROOT}/${review_log}" \
          || halt "$id" "fix agent (review round ${round}) exited non-zero"

        # Re-run the independent test gate; a review-fix that breaks tests halts.
        rtlog="${rundir}/test-after-fix-${round}.log"
        log "re-running test gate after fix round ${round}"
        eval "$TEST_CMD" >"$rtlog" 2>&1 || halt "$id" "tests failed after fix round ${round}"

        # Re-commit (full history — distinct commit per fix round).
        git add -A
        gen_commit_subject "${rundir}/commit-msg-fix-${round}.txt"
        subject="$(first_line "${rundir}/commit-msg-fix-${round}.txt")"
        [ -z "$subject" ] && subject="address review round ${round}"
        git commit -q -m "fix(${id}) review round ${round}: ${subject}" \
          || die "commit failed for ${id} (fix round ${round})"
        log "committed: fix(${id}) review round ${round}: ${subject}"
        # loop back -> re-review against the same base SHA (cumulative diff)
        ;;
    esac
  done

  # ---- close (bash owns beads) --------------------------------------------
  bd close "$id" --reason "ralph-v2: implemented, tests green, review PASS" >/dev/null \
    || die "failed to close ${id}"
  log "closed ${id}"
done

log "completed ${ITERATIONS} iteration(s)"
